# xw_y_am zshell config
# 2018-03-31

config_dir=$(pwd)"/.zsh"

source $config_dir/alias.zsh
source $config_dir/exports.zsh
source $config_dir/completion.zsh
source $config_dir/prompt.zsh

plugin_dir="/opt/config/zsh"

source $plugin_dir/zsh-autosuggestions/zsh-autosuggestions.zsh
source $plugin_dir/pm/zsh/pm.zsh
