# xw_y_am zshell config
# 2018-03-31

config_dir=$(echo $HOME)"/.zsh"

source $config_dir/alias.zsh
source $config_dir/exports.zsh
source $config_dir/completion.zsh
source $config_dir/prompt.zsh

plugin_dir=$config_dir"/plugins"

source $plugin_dir/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $plugin_dir/zsh-autosuggestions/zsh-autosuggestions.zsh
source $plugin_dir/pm/zsh/pm.zsh
