./configure \
  --with-features=huge \
  --enable-gpm \
  --enable-acl \
  --with-x=no \
  --disable-gui \
  --enable-multibyte \
  --enable-cscope \
  --enable-pythoninterp=yes \
  #--enable-python3interp=yes \
  --with-python-command=/bin/python \
